### ISSUE TITLE
Feature: --tags option

### ISSUE THREAD

**Issue by maxarndt** [jimschubert/query-tag-action#1]
Hey Jim!

This action looks great! Thanks so far!

I'm currently using `git describe --tags` in a few projects and thinking about replacing my current CI/CD solution with GitHub Actions.

Is there a chance to add the `--tags` option to your action?
```
       --tags
           Instead of using only the annotated tags, use any tag found in refs/tags namespace. This
           option enables matching a lightweight (non-annotated) tag.
```

Or are there any conflicts with the existing inputs of your action?

**Comment by maxarndt** [comment]
I just saw that you are already using the --tags option in the _Testing_ section of your readme.

If you draw attention to this a little earlier or more clearly, it will certainly be helpful for one or the other interested person.

Thank's for your work!

**Comment by jimschubert** [comment]
Sorry, I've just seen that you'd opened and then closed this.

I added some clarity at the top of the README that it's specifically `git describe --tags` underneath. See 28ed6dfae7a38636a9a0df2eef42a7cdbf8266c6
