### ISSUE TITLE
get rid of  --abbrev=0

### ISSUE THREAD

**Issue by hannesa2** [jimschubert/query-tag-action#3]
I want to see output from `git describe --tags` which deliveres

> 6.1.0-27-gb293759

I do this

      - name: Find Tag
        id: tagger
        uses: jimschubert/query-tag-action@v1
        with:
          skip-unshallow: 'true'
      - name: Show Tag
        id: display
        run: |
          echo 'Output from Find Tag: ${{steps.tagger.outputs.tag}}'

And see in action log as output 

`git describe --tags --abbrev=0 --match '*'  'HEAD~'`  and delivers

> 6.1.0

**Without `--abbrev=0` and 'HEAD~'` I would see expected value how to archive this ?**

eg. 

`git describe --tags --match '*' 

> 6.1.0-27-gb293759

**Comment by jimschubert** [comment]
Try:

```
abbrev: false
commit-ish: HEAD
```

**Comment by jimschubert** [comment]
To explain, abbrev is already optional via #2. I just would need to update the README. GitHub UI should show the option.

There's no option to remove the commit/ref identifier, but git describe defaults to `HEAD` if none is provided. Explicitly passing `HEAD` is the same effect.

**Comment by hannesa2** [comment]
Thank you, it works properly !

Btw, please write all your "secrets" to `README.md`

**Comment by jimschubert** [comment]
> Thank you, it works properly !
> 
> Btw, please write all your "secrets" to `README.md`

No problem.

commit-ish usage and HEAD default are already in README. I doubt abbrev had much to do with your issue, but can't really say without seeing the git repo.

**Comment by hannesa2** [comment]
Here is use it https://github.com/hannesa2/mediapipe/pull/31/files

**Comment by jimschubert** [comment]
Thanks for the quick reply. I'll be sure to check it out!
