### ISSUE TITLE
Node.js 16 actions are deprecated.

### ISSUE THREAD

**Issue by dbouclier** [jimschubert/query-tag-action#9]
When using this action, we got this warning:

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: jimschubert/query-tag-action@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by jimschubert** [comment]
Thanks for the contribution! Available now in v2.2.
